### ISSUE TITLE
Bugs in der Berechnung von Ressourcen

### ISSUE THREAD

**Issue by m-gora** [m-gora/Roll20-Charactersheet-HeXXen1733#10]
HP : unempfindlichkeit fliesst nicht in die berechnung ein, freitextfeld für max hp benötigt

Felder für maximum ressourcen durch sondereffekte (hp, ini, Coups, ideen)

**Comment by Yariloira** [comment]
Ähnlich: Erhöhung Ini durch Reflexe wird nicht mit eingerechnet.

**Comment by m-gora** [comment]
In Version 1.0.3 behoben. Release wird demnächst auf Roll20 Public. 
I.d.R. kommen die Änderungen immer am Montag live.
