### ISSUE TITLE
Würfelergebnis falsch?

### ISSUE THREAD

**Issue by Stonewall6165** [m-gora/Roll20-Charactersheet-HeXXen1733#5]
Hallo, irgendwie ist das Ergebnis falsch, ich weiß aber nicht warum.  Er zieht dann ein anderes Würfelergebnis ab. Bei Ergebnis steht 0.

![image](https://user-images.githubusercontent.com/10817183/102269253-aa13f180-3f1c-11eb-81a9-9763380ff2e9.png)

**Comment by m-gora** [comment]
Hallo @Stonewall6165 ,

Du hast mit einem Malus von -5 gewürfelt, wenn ich das richtig sehe?
Die Maluswürfel werden von dem Würfelergebnis abgezogen  (1 Erfolg bei den HeXXenwürfeln - 1 Erfolg bei den Januswürfeln).

Kannst du mir mal genau aufschreiben wie hoch dein Fertigkeitswert und Attribut war und gegen welchen Malus du gewürfelt hast? Dann überprüfe ich das nochmal.

VG,
Marco

**Comment by Stonewall6165** [comment]
Ahhh, der Malus war drin. Danke.
