### ISSUE TITLE
Pläne für weitere Ressourcen und Hexenjagd?

### ISSUE THREAD

**Issue by Gorthian** [m-gora/Roll20-Charactersheet-HeXXen1733#6]
Gibt es Pläne auch die "neuen" Rollen und Ressourcen aus Hexenjagd und Hexenzorn zu unterstützen?

Ich vermisse z.B. die Möglichkeit Rage und Ambitionen vorzuhalten.
Außerdem fehlt die Fertigkeit "Hexenkunst"

**Comment by m-gora** [comment]
Hallo @Gorthian,

Leider habe ich nur das Grundregelwerk im Besitz.

Wenn der Sheet für die Erweiterungen erweitert werden muss, würde ich dich bitten in dem Issue hier aufzuschreiben was fehlt und wie es mechanisch funktioniert (darunter fällt auch die Fertigkeit Hexenkunst, die im Grundregelwerk nicht enthalten ist). Dann werde ich das gerne integrieren.

VG,
Marco

**Comment by Gorthian** [comment]
Danke für die Antwort.

Rage und Ambitionen sind im Prinzip Ressourcen wie die Segnungen. Beides kann man bis zu einem Maximum von 5 ansammeln.
Allerdings kann man nicht gleichzeitig über Segnungen und Rage verfügen. Erhält man Rage während man noch Segnungen hat, reduzieren sich statt dessen die Segnungen. (Und umgekehrt)

Die Hexenkunst ist einfach eine neue Fertigkeit wie Redekunst, Erste Hilfe und Co, die aber nur bestimmten Rollen zur Verfügung steht.

Details findest Du hier:

- [http://hexxen1733-regelwiki.de/index.php/hexenkunst-wis.html](http://hexxen1733-regelwiki.de/index.php/hexenkunst-wis.html)
- [http://hexxen1733-regelwiki.de/index.php/reg_ambition_und_rage.html](http://hexxen1733-regelwiki.de/index.php/reg_ambition_und_rage.html)

Ich habe auch einen eigenen Custom-Sheet entwickelt, den ich für meine eigenen Runden benutze, in dem ich die neuen Ressourcen mit abdecke.
Gerne kannst Du Dich auch da orientieren: [https://github.com/Gorthian/HeXXen1733_Custom_Character_Sheet](https://github.com/Gorthian/HeXXen1733_Custom_Character_Sheet)

**Comment by Gorthian** [comment]
Blöde Frage:

Ich habe mittlerweile einige postive Feedbacks auf mein Sheet bekommen und wurde auch gefragt, ob ich das nicht als Community-Sheet zur Verfügung stellen könnte.

Das hätte ich im Prinzip gerne gemacht, nur leider weißt Roll20 meine Pille Requests zurück, weil sie lediglich einen Sheet je System zulassen möchten.

Du scheinst Deinen Sheet intern ja mit pugjs zu entwickeln, wovon ich wiederum keinen Ahnung habe.

D.h. wenn ich meine Änderungen in Deinen Roll20-Sheet einbauen würde könntest Du das vermutlich nie wieder zurück in Dein Projekt mergen.

Hast Du denn vor das Sheet weiter zu entwickeln und auch die kommenden Funktionen aus dem Mare Monstrum Crowdfunding einzubauen?
Oder war das Sheet für Dich eher eine "Fingerübung" und wird eher nicht mehr weiter entwickelt?

**Comment by m-gora** [comment]
Hallo @Gorthian,

Ich habe tatsächlich geplant den Sheet weiterzuentwickeln.

Ursprünglich hatte ich vor ein mal im Quartal ein Release herauszubringen.
Unter Milestones kannst du sehen was geplant ist.
Ich versuche noch mein Release-Plan einzuhalten und bis zum 1. April eine neue Version herauszubringen. ;)

Kontributionen würden mir das Leben euch deutlich einfacher machen. Es muss nicht in Form von Code sein.
Es reicht auch aus einfach ein detailliertes Issue zu schreiben, so dass ich nicht noch viel Recherche reinstecken muss.

Da ich selbst vor habe das System zu leiten (hoffentlich noch dieses Jahr) werde ich die Features auch alle selbst brauchen.

VG,
Marco

**Comment by m-gora** [comment]
@Gorthian ,

Ich hab die Zeit mal genutzt die fehlenden Features hinzuzufügen. 
Wenn du möchtest, kannst du den sheet in deiner Sheet Sandbox austesten und feedback geben, ob ich es korrekt umgesetzt habe.

Die aktuellen Changes sind auf dem develop branch.

VG,
Marco

**Comment by m-gora** [comment]
[dist.zip](https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/files/5932409/dist.zip)

Falls du das Projekt nicht selbst bauen kannst, hier der build.

**Comment by m-gora** [comment]
Merged nach master

**Comment by Gorthian** [comment]
Sorry das ich mich jetzt erst melde, aber aktuell fehlt mir ein wenig die Zeit, da ich mich stärker auf meinen Bogen konzentriere.
Das hilft uns aktuell für die laufende Runde einfach mehr...

Deine ZIP-Datei von oben, wird bei mir übrigens leer entpackt.

**Comment by m-gora** [comment]
Hallo @Gorthian,

mein Fehler. Aber mittlerweile wurde mein Branch auch auf roll20 gemerged. Die Changes sind also auch schon live verfuegbar.

VG,
Marco

**Comment by m-gora** [comment]
Es wurden ein paar Probleme mit den neuen Ressourcen aus Hexenjagd in der Version 1.0.3 (hoffentlich entgültig) behoben.
Daher mach ich hier erstmal zu.
