### ISSUE TITLE
Fehler bei Würfelproben

### ISSUE THREAD

**Issue by Yariloira** [m-gora/Roll20-Charactersheet-HeXXen1733#8]
Bei allen Würfelproben wird automatische eine 5er Erschwernis berechnet, auch wenn keine ausgewählt wird!

**Comment by m-gora** [comment]
Hallo @Yariloira,

kannst du mir davon mal einen Screenshot an dieses Ticket anhängen?
Ich hab es gerade in meiner Kampagne getestet und dort funktioniert es.

![image](https://user-images.githubusercontent.com/3631418/111921626-da2bdd00-8a95-11eb-8e35-7dcc246bfd1d.png)

4d6>5 für die Fertigkeit und 0d6>4 für die schwierigkeit. 

VG,
Marco

**Comment by Yariloira** [comment]
Erschwernis/Erleichterung: "Keine"
![Roll20_HeXXen_Würfelfehler 1](https://user-images.githubusercontent.com/81116785/112391571-68070280-8cf8-11eb-8b4f-7fc181a43ce3.png)

Erschwernis / Erleichterung: „Erleichterung 5“
![Roll20_HeXXen_Würfelfehler 2](https://user-images.githubusercontent.com/81116785/112391611-7523f180-8cf8-11eb-94fe-1689d2e33c88.png)

**Comment by m-gora** [comment]
Hallo @Yariloira ,

möchtest du mich vielleicht mal in deine Kampagne einladen? In meiner Kampagne funktioniert es einwandfrei.
Wenn ich "Erleichterung 5" wähle würfel ich 5d6 und bekomme die Erfolge addiert. Bzw bei Erschwernis subtrahiert. 

VG,
Marco

**Comment by Yariloira** [comment]
Wir haben testweise ein neues Spiel generiert und da taucht derselbe Fehler auf. Daher gehe ich davon aus, dass es kein Bug in dem konkreten Spiel ist, sondern ein Fehler im Bogen.

**Comment by m-gora** [comment]
Joine mal dieser Kampagne: https://app.roll20.net/join/4936548/3VdU2g

**Comment by Yariloira** [comment]
Das ist unsere: https://app.roll20.net/join/10226628/_nW1kQ

**Comment by m-gora** [comment]
Problem scheint wohl nur für neue Character Sheets seit dem letzten Patch aufzutreten.
Ich schaue mir das zeitnah genauer an.

**Comment by m-gora** [comment]
Neue Charakterbögen werden anscheinen mit allen Schadensarten auf maximum angelegt. 
Das sollte nicht der Fall sein und erklärt das Verhalten.

Die Berechnung der Gewürfelten Januswürfel erfolgt folgendermaßen:

-max(Lähmungsschaden + Schwierigkeit, 5)d6

So ist sichergestellt, das immer maximal 5 Januswürfel gewürfelt werden.

Ich gehe dem Problem mit der Standardeinstellung beim Schaden nach.
Bis dahin bitte alle Schadensarten nach Anlegen der Sheets auf 0 setzen.

VG,
Marco

**Comment by m-gora** [comment]
In Version 1.0.3 behoben.
